<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>PodgotovkaDll</RootNamespace>
    <AssemblyName>PodgotovkaDll</AssemblyName>
    
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <PackageId>Frensqq.PodgotovkaDll</PackageId>
    <Description>Test CiCdLibrary</Description>
    <PackageTags>encoding;converter;utf8;windows1251;ascii;koi8r;utf16</PackageTags>
    <Version>1.0.0</Version>

  </PropertyGroup>
</Project>