name: Publish to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Restore NuGet packages
      run: nuget restore PodgotovkaDll.sln
    
    - name: Build
      run: msbuild PodgotovkaDll.sln /p:Configuration=Release
    
    - name: Create NuGet package
      run: msbuild PodgotovkaDll.csproj /p:Configuration=Release /p:PackageOutputPath=./nupkgs /t:Pack
    
    - name: Publish to GitHub Packages
      run: nuget push "nupkgs/*.nupkg" -Source "https://nuget.pkg.github.com/frensqq/index.json" -ApiKey ${{ secrets.GITHUB_TOKEN }} -SkipDuplicate